org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

projectGroup=dev.lunabridge
projectVersion=0.3.0-beta.6
javaToolchainVersion=25
paperJavaVersion=25
velocityJavaVersion=25
paperApiVersion=26.2.build.117-stable
velocityApiVersion=4.1.0-SNAPSHOT
lunaChatApiVersion=1.0.0-SNAPSHOT
jdaVersion=6.4.1
junitVersion=5.10.2
